### ISSUE TITLE
Black Screen in Quest2 Browser

### ISSUE THREAD

**Issue by AbdullahBurhan** [De-Panther/unity-webxr-export#173]
I have downloaded  the latest version in Github, and I am using Unity 2019.4.20,
black screen appears when using the Oculus browser or firefox Reality in Quest2, it was working before the latest update for the oculus browser.
it is working in Quest1.

**Comment by De-Panther** [comment]
I only have Quest 1.
Is the WebXR Export demo also stuck in a black screen?
https://de-panther.github.io/unity-webxr-export/Build

**Comment by AbdullahBurhan** [comment]
Yes the demo stuck as well, but an error occur while loading the content,
this error or the black screen (on Firefox Reality) started to occur after the latest update of the oculus browser.
NOTE : The old version of WebXR exporter is working.
![com oculus shellenv-20211007-102236](https://user-images.githubusercontent.com/41993944/136338943-ad668de5-9476-4482-a111-c108b006cc8c.jpg)

**Comment by De-Panther** [comment]
It's a Unity bug. You'll get the "GetProcAddress" error with all the Unity WebGL content in the latest Oculus Browser.
You can go to the browser flags and disable the EXT_multisampled_render_to_texture.

It shouldn't happen in FirefoxReality, as they didn't implement this extension

**Comment by AbdullahBurhan** [comment]
The issue has been fixed

**Comment by De-Panther** [comment]
It's not fixed yet IMO, but it's now the responsibility of both the Unity WebGL and Oculus Browser teams.
The Unity team worked on a fix that would get to some versions of the engine.
The Oculus Browser team and the WebGL standard team need to decide if they rename the extension for current and older Unity WebGL builds to work.

Informing the user to disable a flag is not a solution.

I'm keeping this thread open for when I'll have more news. (Hope good news)

**Comment by FaberVi** [comment]
Same problem here.

**Comment by De-Panther** [comment]
The WebGL standard group and the Oculus Browser team renamed the extension, next version of Oculus Browser have a fix.
They release a new version once around 2 weeks.

**Comment by De-Panther** [comment]
Oculus Browser 17.2 is rolling out with a fix
